[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_archive = false
build_flags = -Os -DCORE_DEBUG_LEVEL=0

lib_deps =
  adafruit/Adafruit NeoPixel@^1.15.1
  forkineye/ESPAsyncE131@^1.0.5
  esphome/ESPAsyncWebServer-esphome@^3.1.0
  esphome/AsyncTCP-esphome@^2.0.0
